# Generated by Django 6.1.1 on 2026-09-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interseccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'intersección',
                'verbose_name_plural': 'intersecciones',
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('local', 'Cámara del dispositivo'), ('rtsp', 'Cámara IP (RTSP)')], default='local', max_length=10)),
                ('url_rtsp', models.CharField(blank=True, help_text='Solo para cámaras IP. Se usará cuando se integre la IA.', max_length=300)),
                ('activa', models.BooleanField(default=True)),
                ('interseccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='camaras.interseccion')),
            ],
        ),
    ]
