# Generated by Django 6.1.1 on 2026-09-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_tiempo', models.DateTimeField(db_index=True)),
                ('clase', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='camaras.camara')),
            ],
            options={
                'verbose_name': 'conteo de vehículos',
                'verbose_name_plural': 'conteos de vehículos',
                'indexes': [models.Index(fields=['camara', 'marca_tiempo'], name='camaras_con_camara__0df4f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('camara', 'marca_tiempo', 'clase'), name='conteo_unico_por_minuto_y_clase')],
            },
        ),
    ]
